In [2]:
import matplotlib.pyplot as pyplot
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv("epl_final.csv")

In [4]:
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,14,4,6,6,13,12,1,2,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,10,5,7,7,19,14,1,2,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,3,9,8,4,15,21,5,3,1,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,4,6,5,8,11,13,1,1,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,8,6,6,4,21,20,1,3,0,0

In [5]:
df.columns

Index(['Season', 'MatchDate', 'HomeTeam', 'AwayTeam', 'FullTimeHomeGoals',
       'FullTimeAwayGoals', 'FullTimeResult', 'HalfTimeHomeGoals',
       'HalfTimeAwayGoals', 'HalfTimeResult', 'HomeShots', 'AwayShots',
       'HomeShotsOnTarget', 'AwayShotsOnTarget', 'HomeCorners', 'AwayCorners',
       'HomeFouls', 'AwayFouls', 'HomeYellowCards', 'AwayYellowCards',
       'HomeRedCards', 'AwayRedCards'],
      dtype='str')

In [6]:
df.HomeTeam.nunique()

46

In [7]:
len(df)

9380

In [8]:
data = {}

for col in df.columns:
    data[col] = {'dtype' : df[col].dtype, 'nunique' : df[col].nunique(), 'null' : df[col].isnull().sum()}

In [9]:
data

{'Season': {'dtype': <StringDtype(storage='python', na_value=nan)>,
  'nunique': 25,
  'null': np.int64(0)},
 'MatchDate': {'dtype': <StringDtype(storage='python', na_value=nan)>,
  'nunique': 2599,
  'null': np.int64(0)},
 'HomeTeam': {'dtype': <StringDtype(storage='python', na_value=nan)>,
  'nunique': 46,
  'null': np.int64(0)},
 'AwayTeam': {'dtype': <StringDtype(storage='python', na_value=nan)>,
  'nunique': 46,
  'null': np.int64(0)},
 'FullTimeHomeGoals': {'dtype': dtype('int64'),
  'nunique': 10,
  'null': np.int64(0)},
 'FullTimeAwayGoals': {'dtype': dtype('int64'),
  'nunique': 10,
  'null': np.int64(0)},
 'FullTimeResult': {'dtype': <StringDtype(storage='python', na_value=nan)>,
  'nunique': 3,
  'null': np.int64(0)},
 'HalfTimeHomeGoals': {'dtype': dtype('int64'),
  'nunique': 6,
  'null': np.int64(0)},
 'HalfTimeAwayGoals': {'dtype': dtype('int64'),
  'nunique': 6,
  'null': np.int64(0)},
 'HalfTimeResult': {'dtype': <StringDtype(storage='python', na_value=nan)>,
  'nunique': 3,
  'null': np.int64(0)},
 'HomeShots': {'dtype': dtype('int64'), 'nunique': 40, 'null': np.int64(0)},
 'AwayShots': {'dtype': dtype('int64'), 'nunique': 33, 'null': np.int64(0)},
 'HomeShotsOnTarget': {'dtype': dtype('int64'),
  'nunique': 24,
  'null': np.int64(0)},
 'AwayShotsOnTarget': {'dtype': dtype('int64'),
  'nunique': 21,
  'null': np.int64(0)},
 'HomeCorners': {'dtype': dtype('int64'), 'nunique': 21, 'null': np.int64(0)},
 'AwayCorners': {'dtype': dtype('int64'), 'nunique': 20, 'null': np.int64(0)},
 'HomeFouls': {'dtype': dtype('int64'), 'nunique': 30, 'null': np.int64(0)},
 'AwayFouls': {'dtype': dtype('int64'), 'nunique': 29, 'null': np.int64(0)},
 'HomeYellowCards': {'dtype': dtype('int64'),
  'nunique': 8,
  'null': np.int64(0)},
 'AwayYellowCards': {'dtype': dtype('int64'),
  'nunique': 10,
  'null': np.int64(0)},
 'HomeRedCards': {'dtype': dtype('int64'), 'nunique': 4, 'null': np.int64(0)},
 'AwayRedCards': {'dtype': dtype('int64'), 'nunique': 3, 'null': np.int64(0)}}

In [11]:
df.isna().sum()

Season               0
MatchDate            0
HomeTeam             0
AwayTeam             0
FullTimeHomeGoals    0
FullTimeAwayGoals    0
FullTimeResult       0
HalfTimeHomeGoals    0
HalfTimeAwayGoals    0
HalfTimeResult       0
HomeShots            0
AwayShots            0
HomeShotsOnTarget    0
AwayShotsOnTarget    0
HomeCorners          0
AwayCorners          0
HomeFouls            0
AwayFouls            0
HomeYellowCards      0
AwayYellowCards      0
HomeRedCards         0
AwayRedCards         0
dtype: int64

In [13]:
df.describe()

,FullTimeHomeGoals,FullTimeAwayGoals,HalfTimeHomeGoals,HalfTimeAwayGoals,HomeShots,AwayShots,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
count,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000
mean,1.535394,1.182623,0.688273,0.518763,13.617484,10.810661,5.973134,4.693710,6.040299,4.774733,11.276333,11.765672,1.468124,1.792431,0.062473,0.085288
std,1.305432,1.157414,0.835079,0.735357,5.356424,4.696501,3.267954,2.750045,3.110619,2.749541,3.750250,3.924179,1.217190,1.288481,0.253221,0.290183
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,7.000000,4.000000,3.000000,4.000000,3.000000,9.000000,9.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,10.000000,6.000000,4.000000,6.000000,4.000000,11.000000,12.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,14.000000,8.000000,6.000000,8.000000,6.000000,14.000000,14.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,43.000000,37.000000,24.000000,20.000000,20.000000,19.000000,33.000000,29.000000,7.000000,9.000000,3.000000,2.000000

In [14]:
df.Season.unique()

<StringArray>
['2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07',
 '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14',
 '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', '2020/21',
 '2021/22', '2022/23', '2023/24', '2024/25']
Length: 25, dtype: str